### ISSUE TITLE
Drop support for qualified paths in Web API

### ISSUE THREAD

**Issue by dcastro** [serokell/coffer#113]
# Clarification and motivation

This issue is blocked by #95 

Once that issue is done, using `QualifiedPath` in the Web API will become redundant.
The backend config is included in the request, and there's only one possible backend to connect to, so qualifying the path with a backend name would not make sense.

We should make sure only regular `Path` and `EntryPath`s are used in the Web API.

# Acceptance criteria

* The Web API's endpoints do not accept / return `QualifiedPath`s.

**Comment by Kariel-Myrr** [comment]
If we're going to get rid of `QualifiedPath` but we're still have to configure it for `CLI.Types`

<img width="732" alt="Снимок экрана 2022-07-05 в 11 08 52" src="https://user-images.githubusercontent.com/44503389/177281242-2c2e94ee-ae08-4231-a7bb-ca65d0f4b6e6.png">

QualifiedPath requires BackendName, to reduce code and unnecessary `backend` passing down the functions we can name every Web API backend as 'web-api-backend'. It's possible because we have only one backend for each request
Also it would reduce name field in header, which is seems redundant

So now we can just pack every Path/EntryPath to QualifiedPath with 'web-api-backend'
