### ISSUE TITLE
Use one style for showing parsing errors

### ISSUE THREAD

**Issue by sancho20021** [serokell/coffer#98]
# Clarification and motivation

Currently CLI uses different styles to signal syntax errors.

## Examples:
- **sort**
```
>>> coffer find --sort BAD_FORMAT
option --sort: Invalid sort format: "BAD_FORMAT".
Expected format is:
 * to sort by entry name: 'name:<direction>',
 * to sort by the entry's last modified date: 'date:<direction>',
 * to sort by a field's contents: '<fieldname>:contents:<direction>',
 * to sort by a field's last modified date: '<fieldname>:date:<direction>'.
Direction can be 'asc' or 'desc'.
Examples: 'name:desc', 'password:date:asc'.
...
```
- **filter**
```
>>> coffer find --filter BAD_FORMAT
option --filter: Invalid filter format: "BAD_FORMAT".
Expected format is:
 * to filter by entry name: 'name~<substring>',
 * to filter by entry's last modified date: 'date<op><date>',
 * to filter by a field's contents: '<fieldname>:contents~<substring>',
 * to filter by a field's last modified date: '<fieldname>:date<op><date>'.
<op> can be '<=', '>=', '<', '>', or '='.
<date> can be 'YYYY', 'YYYY-MM', 'YYYY-MM-DD', or 'YYYY-MM-DD HH:MM:SS'.
Examples: 'name~vault', 'date<2020-02', 'url:contents~google.com', 'pw:date<2020-02'.

Parser error:
1:11:
  |
1 | BAD_FORMAT
  |           ^
unexpected end of input
expecting ':' or fieldname
...
```
In case of `sort` custom messages are shown, while in `filter`, `megaparsec`'s error messages appear. To keep things consistent, we can use `megaparsec` for both.

# Acceptance criteria

Rewrite parsing of `--sort` option using `megaparsec` instead of `Text.splitOn`.

**Comment by dcastro** [comment]
So, the output of these 2 commands does indeed seem to be inconsistent:

```
coffer find --sort BAD_FORMAT
coffer find --filter BAD_FORMAT
```

And that could be fixed by using megaparsec for parsing the `--sort` value, instead of `Text.splitOn ":"`.

----

Regarding the apparent inconsistency with the output of other commands such as `coffer create ent --tag BAD~`: I would argue that's ok. One could argue that the syntax of that command is valid, it's just that the tag content is invalid. In the first two commands, the syntax of the command was wrong. Therefore, it could be argued that they're different types of errors; therefore, the format of the outputs does not have to be consistent.

**Comment by sancho20021** [comment]
Thanks! With this explanation I totally agree. Indeed, using megaparsec for parsing `--sort` will be good enough. Should I edit the Issue explanation to clarify what exactly we need to change?

**Comment by dcastro** [comment]
> Thanks! With this explanation I totally agree. Indeed, using megaparsec for parsing `--sort` will be good enough. Should I edit the Issue explanation to clarify what exactly we need to change?

Sure, please add a note with the conclusion of our convo ^^
